import {
  Company,
  UserProfile,
  Project,
  RKKDocument,
  RKKCommitment,
  HazardIdentification,
  SafetyRegulation,
  SupervisionTargetProgram,
  Personnel,
  SafetyBudget,
  OrgMember,
  SafetyDocument,
  Inspection,
  Finding,
  JobSafetyAnalysis,
  WorkPermit,
  WeeklyReport,
  MonthlyReport,
  TestingCommissioning,
  FinalEvaluation,
  AuditLog,
  AppNotification,
  RKKTemplate,
} from '../types';

export const initialCompany: Company = {
  id: 'comp-001',
  name: 'PT Mitra Pengawas Konstruksi Prima',
  businessEntity: 'PT',
  nib: '9120003456789',
  address: 'Jl. Jenderal Sudirman No. 45, Gedung Graha Rekayasa Lt. 4',
  province: 'DKI Jakarta',
  regency: 'Jakarta Selatan',
  district: 'Setiabudi',
  phone: '021-5234567',
  email: 'info@mitrapengawas.co.id',
  website: 'https://mitrapengawas.co.id',
  directorName: 'Ir. Bambang Trihatmojo, M.Eng.',
  authorizedRepName: 'Ir. Hendra Wijaya, ST., MT.',
  sbuNumber: 'SBU-01928/LPJK/2024',
  logoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?w=200&auto=format&fit=crop&q=60',
  createdAt: '2024-01-10T08:00:00Z',
  updatedAt: '2026-09-17T08:00:00Z',
};

export const initialUser: UserProfile = {
  id: 'usr-001',
  email: 'azmancivd@gmail.com',
  fullName: 'Ir. Hendra Wijaya, ST., MT.',
  role: 'TEAM_LEADER',
  companyId: 'comp-001',
  position: 'Team Leader / Kepala Pengawas MK',
  phoneNumber: '0812-3456-7890',
  createdAt: '2024-01-10T08:00:00Z',
};

export const initialProjects: Project[] = [
  {
    id: 'proj-001',
    companyId: 'comp-001',
    packageTitle: 'Pengawasan Teknis Pembangunan Gedung Rawat Inap Terpadu RSUD Dr. Soewondo (6 Lantai)',
    projectName: 'Pembangunan Gedung Rawat Inap Terpadu 6 Lantai',
    location: 'Jl. Diponegoro No. 12, Kendal',
    province: 'Jawa Tengah',
    regency: 'Kabupaten Kendal',
    district: 'Kota Kendal',
    village: 'Pegangsaan',
    fundingSource: 'APBN / DAK Fisik Kesehatan',
    budgetYear: '2026',
    contractNumber: 'HK.02.03/KONT-MK/RSUD/2026/04',
    contractDate: '2026-02-15',
    contractValue: 48500000000, // Rp 48,5 Milyar
    startDate: '2026-03-01',
    endDate: '2026-12-25',
    executionPeriodDays: 300,
    maintenancePeriodDays: 180,
    status: 'ACTIVE',

    // Pengguna Jasa
    clientInstitution: 'Dinas Kesehatan & RSUD Dr. Soewondo',
    clientOfficerName: 'Dr. H. Agus Setyanto, Sp.OG',
    clientOfficerPosition: 'Pengguna Anggaran / Direktur RSUD',
    clientOfficerNip: '19740510 200212 1 005',
    clientOfficerPhone: '0294-381123',

    // PPK
    ppkName: 'Ahmad Fauzi, ST., M.Eng.',
    ppkNip: '19780412 200501 1 008',
    ppkPosition: 'Pejabat Pembuat Komitmen (PPK)',
    ppkPhone: '0813-9876-5432',

    // Kontraktor
    contractorName: 'PT Cipta Bangun Perkasa',
    contractorDirector: 'Ir. Rudi Hermanto',
    contractorPhone: '024-7654321',
    contractorAddress: 'Jl. Pemuda No. 88, Semarang',

    // Konsultan Pengawas / MK
    consultantName: 'PT Mitra Pengawas Konstruksi Prima',
    teamLeaderName: 'Ir. Hendra Wijaya, ST., MT.',
    consultantPhone: '021-5234567',

    createdAt: '2026-02-16T08:00:00Z',
    updatedAt: '2026-09-17T08:00:00Z',
    createdBy: 'usr-001',
  },
  {
    id: 'proj-002',
    companyId: 'comp-001',
    packageTitle: 'Pengawasan Teknis Pembangunan Jembatan Sei Rengas Bentang 80 M',
    projectName: 'Pembangunan Jembatan Rangka Baja Sei Rengas',
    location: 'Lintas Pesisir Barat Km 45',
    province: 'Kalimantan Barat',
    regency: 'Kabupaten Kubu Raya',
    district: 'Sungai Kakap',
    fundingSource: 'APBN SBSN',
    budgetYear: '2026',
    contractNumber: '04/KTR/PJ-KBR/2026',
    contractDate: '2026-01-20',
    contractValue: 32000000000,
    startDate: '2026-02-01',
    endDate: '2026-10-31',
    executionPeriodDays: 270,
    maintenancePeriodDays: 365,
    status: 'ACTIVE',
    clientInstitution: 'Balai Pelaksanaan Jalan Nasional (BPJN) Kalimantan Barat',
    clientOfficerName: 'Ir. Raden Sumarno, MT.',
    clientOfficerPosition: 'Kepala Satuan Kerja PJN Wilayah I',
    clientOfficerNip: '19720315 199803 1 003',
    ppkName: 'Budi Santoso, ST.',
    ppkNip: '19810620 200801 1 012',
    ppkPosition: 'PPK 1.3 BPJN Kalbar',
    contractorName: 'PT Wira Karya Nusa',
    contractorDirector: 'Drs. H. Mulyadi',
    consultantName: 'PT Mitra Pengawas Konstruksi Prima',
    teamLeaderName: 'Dedy Kurniawan, ST., M.Sc.',
    createdAt: '2026-01-25T08:00:00Z',
    updatedAt: '2026-09-17T08:00:00Z',
    createdBy: 'usr-001',
  },
];

export const initialRKKDocument: RKKDocument = {
  id: 'rkk-001',
  projectId: 'proj-001',
  documentNumber: 'RKK-MK/RSUD-KDL/2026/01',
  rkkNumber: 'RKK-01-REV00',
  version: 'Rev.00',
  date: '2026-03-05',
  status: 'APPROVED',
  preparedBy: 'Drs. Wahyu Prasetyo, ST. (Ahli K3 Konstruksi)',
  reviewedBy: 'Ir. Hendra Wijaya, ST., MT. (Team Leader)',
  approvedBy: 'Ahmad Fauzi, ST., M.Eng. (PPK RSUD Kendal)',
  revisionNotes: 'Penerbitan dokumen RKK Konsultansi Pengawasan Awal sesuai Permen PUPR No. 10 Tahun 2021',
  isLocked: false,
  qrVerificationCode: 'VERIFY-RKK-MK-RSUD-2026-KNDL-001',
  createdAt: '2026-03-02T08:00:00Z',
  updatedAt: '2026-09-17T08:00:00Z',
};

export const initialCommitment: RKKCommitment = {
  id: 'com-001',
  rkkId: 'rkk-001',
  companyName: 'PT Mitra Pengawas Konstruksi Prima',
  packageName: 'Pengawasan Teknis Pembangunan Gedung Rawat Inap Terpadu RSUD Dr. Soewondo (6 Lantai)',
  city: 'Kendal',
  date: '2026-03-05',
  headSupervisorName: 'Ir. Hendra Wijaya, ST., MT.',
  headSupervisorPosition: 'Kepala Pengawas Pekerjaan (Team Leader)',
  commitmentPoints: [
    'Pemenuhan ketentuan Keselamatan Konstruksi telah sesuai dengan Dokumen RKK;',
    'Pengawasan mengacu kepada Kerangka Acuan Kerja (KAK);',
    'Pengawasan pelaksanaan berdasarkan kesesuaian standar dan desain;',
    'Pengawasan pelaksanaan pekerjaan sesuai dengan Standar Operasional Prosedur (SOP); dan',
    'Menggunakan tenaga kerja yang berkompeten dan bersertifikat.',
  ],
};

export const initialHazards: HazardIdentification[] = [
  {
    id: 'haz-001',
    rkkId: 'rkk-001',
    orderNumber: 1,
    activityDescription: 'Pengawasan Pekerjaan Galian Tanah Basement & Pondasi Bore Pile kedalaman > 3 meter',
    workStage: 'Pekerjaan Struktur Bawah & Tanah',
    supervisionActivity: 'Pengawasan kemiringan dinding galian (sloping/shoring), pemasangan dewatering, dan stabilitas lereng galian',
    hazardIdentification: 'Dinding galian longsor mendadak, genangan air rembesan, gas berbahaya di dasar galian',
    riskDescription: 'Pekerja dan pengawas tertimbun material longsor, tenggelam/terperosok, asfiksia akibat gas beracun',
    probability: 3,
    severity: 4,
    riskScore: 12,
    riskLevel: 'Sedang',
    initialControls: [
      'Rekayasa Teknis: Dinding Penahan Tanah (Sheet Pile) & Terpal Pelindung Lereng',
      'Administratif: Izin Kerja Galian (Permit to Work > 2m) & JSA sebelum penggalian',
      'Administratif: Pemasangan Barricade & Rambu Peringatan Bahaya Longsor di sekeliling galian',
      'APD: Helm K3, Sepatu Safety anti-slip, Rompi reflektif, Gas Detector portable',
    ],
    residualProbability: 1,
    residualSeverity: 2,
    residualRiskScore: 2,
    residualRiskLevel: 'Kecil',
    followUpControls: 'Inspeksi harian stabilitas lereng oleh Pengawas K3 sebelum jam kerja dimulai, penyediaan tangga darurat akses tiap 15m.',
    pic: 'Safety Engineer & Inspector Sipil',
    supportingDoc: 'SOP-GALIAN-01 / Form PTW-EXCAVATION',
    status: 'SESUAI',
  },
  {
    id: 'haz-002',
    rkkId: 'rkk-001',
    orderNumber: 2,
    activityDescription: 'Pengawasan Pekerjaan Pengecoran Kolom, Balok & Plat Lantai pada Ketinggian (Lantai 2 s/d 6)',
    workStage: 'Pekerjaan Struktur Atas (Beton Bertulang)',
    supervisionActivity: 'Pemeriksaan kekuatan bekisting, perancah (scaffolding), handrail pengaman tepi plat, dan slump test beton',
    hazardIdentification: 'Pekerja jatuh dari ketinggian > 2 meter, material/alat terjatuh menimpa orang di bawah, perancah roboh',
    riskDescription: 'Cedera patah tulang, benturan fatal di kepala, kerusakan aset konstruksi',
    probability: 4,
    severity: 4,
    riskScore: 16,
    riskLevel: 'Besar',
    initialControls: [
      'Rekayasa Teknis: Pemasangan Safety Net di perimeter luar, Toe-board dan Double Handrail di tepi cor',
      'Administratif: Sertifikasi Kelaikan Scaffolding (Green Tagging) oleh Scaffolder bersertifikat',
      'Administratif: Penerbitan Surat Izin Kerja di Ketinggian (Working at Height Permit)',
      'APD: Full Body Harness dengan double lanyard & shock absorber, Helm dengan chinstrap',
    ],
    residualProbability: 1,
    residualSeverity: 3,
    residualRiskScore: 3,
    residualRiskLevel: 'Kecil',
    followUpControls: 'Pemeriksaan 100% titik angkur lifelines, pengawasan ketat saat manuver concrete bucket / pipa concrete pump.',
    pic: 'Ahli K3 Konstruksi & Inspector Struktur',
    supportingDoc: 'IK-KETINGGIAN-03 / Form PTW-HEIGHT',
    status: 'SESUAI',
  },
  {
    id: 'haz-003',
    rkkId: 'rkk-001',
    orderNumber: 3,
    activityDescription: 'Pengawasan Operasional Pesawat Angkat & Angkut (Tower Crane & Mobile Crane)',
    workStage: 'Erection & Pengangkatan Material Berat',
    supervisionActivity: 'Verifikasi kelengkapan SILO (Surat Ijin Layak Operasi), SIO Operator/Rigger, dan checklist inspeksi harian crane',
    hazardIdentification: 'Sling kawat putus saat mengangkat muatan, crane terbalik akibat melebihi Safe Working Load (SWL), radius ayunan melintasi area umum',
    riskDescription: 'Material besi/bekisting jatuh menimpa pekerja, kecelakaan fatal (fatality), kerusakan struktur bangunan sekitar',
    probability: 3,
    severity: 5,
    riskScore: 15,
    riskLevel: 'Besar',
    initialControls: [
      'Rekayasa Teknis: Pemasangan Anemometer pembatas angin dan Limit Switch beban otomatis pada crane',
      'Administratif: Pengawasan Rigging Plan & verifikasi batas SWL sebelum pengangkatan',
      'Administratif: Pemasangan perimeter steril radius jangkau crane dengan flagman bertugas',
      'Administratif: Verifikasi SILO Kemnaker dan SIO Kemenaker Operator Kelas 1 & Rigger bersertifikat',
      'APD: Helm K3, Rompi Reflektif, Sarung Tangan Leather Rigger, Sepatu Safety',
    ],
    residualProbability: 1,
    residualSeverity: 3,
    residualRiskScore: 3,
    residualRiskLevel: 'Kecil',
    followUpControls: 'Lifting plan disetujui Team Leader & Safety Engineer sebelum pengangkatan beban kritis di atas 5 ton.',
    pic: 'Inspector Peralatan (ME) & Ahli K3',
    supportingDoc: 'SOP-LIFTING-CRANE-02 / Form JSA-LIFTING',
    status: 'SESUAI',
  },
  {
    id: 'haz-004',
    rkkId: 'rkk-001',
    orderNumber: 4,
    activityDescription: 'Pengawasan Instalasi Mekanikal, Elektrikal & Plumbing (MEP) di Shaft & Ruang Terbatas (Basement)',
    workStage: 'Pekerjaan Mekanikal & Elektrikal',
    supervisionActivity: 'Pengawasan kabel tegangan tinggi sementara, penerangan kerja basement, ventilasi dan gas berbahaya di ground tank',
    hazardIdentification: 'Kabel terkelupas tersengat listrik (electrocution), sirkulasi udara minim, bahaya kebakaran dari pekerjaan las (hot work)',
    riskDescription: 'Luka bakar listrik, keracunan asap las, ledakan/kebakaran di ruang terbatas',
    probability: 3,
    severity: 4,
    riskScore: 12,
    riskLevel: 'Sedang',
    initialControls: [
      'Rekayasa Teknis: Penggunaan stop kontak industri IP54, sistem ELCB/GFCI pencegah korsleting',
      'Administratif: Izin Kerja Panas (Hot Work Permit) dilengkapi APAR 6kg siap pakai berjarak 3 meter',
      'Administratif: Izin Ruang Terbatas (Confined Space) dengan blower exhaust udara segar',
      'APD: Kacamata las/Face shield, masker respirator uap, sarung tangan las, sepatu isolasi',
    ],
    residualProbability: 1,
    residualSeverity: 2,
    residualRiskScore: 2,
    residualRiskLevel: 'Kecil',
    followUpControls: 'Pemeriksaan harian kabel kerja oleh Inspector ME, larangan merokok ketat di seluruh zona dalam ruangan.',
    pic: 'Inspector ME & Petugas K3',
    supportingDoc: 'Form PTW-HOTWORK / Form PTW-CONFINED',
    status: 'SESUAI',
  },
];

export const initialRegulations: SafetyRegulation[] = [
  {
    id: 'reg-001',
    rkkId: 'rkk-001',
    orderNumber: 1,
    methodDescription: 'Keselamatan Umum di Tempat Kerja Konstruksi & Perlindungan Tenaga Kerja',
    regulationTitle: 'Undang-Undang Nomor 1 Tahun 1970 tentang Keselamatan Kerja',
    numberAndYear: 'UU No. 1 Tahun 1970',
    articleClause: 'Pasal 1 ayat (6), Pasal 3 ayat (1), Pasal 8 ayat (1) dan Pasal 9',
    notes: 'Kewajiban penyelenggaraan syarat-syarat keselamatan kerja dan pemeriksaan kesehatan berkala bagi seluruh pekerja.',
  },
  {
    id: 'reg-002',
    rkkId: 'rkk-001',
    orderNumber: 2,
    methodDescription: 'Standar Keamanan, Keselamatan, Kesehatan, dan Keberlanjutan (K4) Jasa Konstruksi',
    regulationTitle: 'Undang-Undang Nomor 2 Tahun 2017 tentang Jasa Konstruksi',
    numberAndYear: 'UU No. 2 Tahun 2017',
    articleClause: 'Pasal 59, Pasal 70 & Pasal 84',
    notes: 'Kewajiban Pengguna Jasa dan Penyedia Jasa memenuhi standar K4 dalam setiap penyelenggaraan jasa konstruksi.',
  },
  {
    id: 'reg-003',
    rkkId: 'rkk-001',
    orderNumber: 3,
    methodDescription: 'Pedoman Sistem Manajemen Keselamatan Konstruksi (SMKK) dan Format Dokumen RKK Konsultansi Pengawasan',
    regulationTitle: 'Peraturan Menteri PUPR Nomor 10 Tahun 2021 tentang Pedoman Sistem Manajemen Keselamatan Konstruksi',
    numberAndYear: 'Permen PUPR No. 10/2021',
    articleClause: 'Pasal 4, Pasal 7, Pasal 15, Pasal 26 & Lampiran D.1 (Format RKK Pengawasan/MK)',
    notes: 'Acuan utama dalam penyusunan dokumen RKK Pengawasan/MK, IBPRP, 9 komponen biaya SMKK, dan penilaian RKK.',
  },
  {
    id: 'reg-004',
    rkkId: 'rkk-001',
    orderNumber: 4,
    methodDescription: 'Metode Pengawasan Bekerja pada Ketinggian (Perancah, Bekisting, & Struktur Atas)',
    regulationTitle: 'Peraturan Menteri Ketenagakerjaan tentang Keselamatan dan Kesehatan Kerja pada Ketinggian',
    numberAndYear: 'Permenaker No. 9 Tahun 2016',
    articleClause: 'Pasal 2, Pasal 14, Pasal 25 s/d Pasal 35',
    notes: 'Kewajiban penyiapan jalur angkur, lifelines, perancah bersertifikat, dan penggunaan full body harness.',
  },
  {
    id: 'reg-005',
    rkkId: 'rkk-001',
    orderNumber: 5,
    methodDescription: 'Pengawasan Pesawat Angkat dan Angkut (Tower Crane, Hoist, & Mobile Crane)',
    regulationTitle: 'Peraturan Menteri Ketenagakerjaan tentang Keselamatan dan Kesehatan Kerja Pesawat Angkat dan Pesawat Angkut',
    numberAndYear: 'Permenaker No. 8 Tahun 2020',
    articleClause: 'Pasal 6, Pasal 15, Pasal 137 s/d Pasal 150',
    notes: 'Kewajiban sertifikasi SILO untuk crane dan lisensi SIO Kemenaker untuk Operator dan Juru Ikat (Rigger).',
  },
];

export const initialSupervisionPrograms: SupervisionTargetProgram[] = [
  {
    id: 'prog-001',
    rkkId: 'rkk-001',
    orderNumber: 1,
    activityDescription: 'Pengawasan Pekerjaan Galian Tanah Basement kedalaman > 3 meter',
    target: '1. Galian tanah basement tidak terjadi longsor.\n2. Tidak ada pekerja/pengawas tertimbun.\n3. Galian sesuai batas dan kedalaman spesifikasi teknis.',
    supervisionProgram: '1. Memastikan metode pelaksanaan perkuatan shoring / retaining wall terpasang sebelum penggalian lanjutan.\n2. Melakukan verifikasi Izin Kerja Galian (PTW) harian.\n3. Melakukan inspeksi harian terhadap rambu dan barikade tepi galian.',
    benchmark: 'Zero Accident pada galian tanah, lereng stabil sesuai sudut aman, barikade lengkap terpasang 100%.',
    pic: 'Ahli K3 Pengawasan & Inspector Sipil',
    schedule: 'Minggu ke-1 s/d Minggu ke-8 (Setiap Hari)',
    status: 'TERLAKSANA',
  },
  {
    id: 'prog-002',
    rkkId: 'rkk-001',
    orderNumber: 2,
    activityDescription: 'Pengawasan Pekerjaan Struktur Beton Bertulang pada Ketinggian (Lantai 2 s.d 6)',
    target: '1. Zero accident pekerja jatuh dari ketinggian.\n2. Zero accident tertimpa material jatuh.\n3. Perancah dan bekisting terpasang kokoh sesuai perhitungan struktur.',
    supervisionProgram: '1. Memastikan inspeksi scaffolding mingguan dan penempelan Green Tag laik pakai.\n2. Memastikan seluruh pekerja mengenakan Full Body Harness terikat pada lifeline kawat baja.\n3. Memastikan safety net perimeter lantai aktif terpasang.',
    benchmark: 'Tingkat kepatuhan APD Ketinggian 100%, Green Tagging scaffolding 100%, Zero LTI (Lost Time Injury).',
    pic: 'Team Leader & Ahli K3 Pengawasan',
    schedule: 'Minggu ke-9 s/d Minggu ke-32',
    status: 'SEDANG_BERJALAN',
  },
  {
    id: 'prog-003',
    rkkId: 'rkk-001',
    orderNumber: 3,
    activityDescription: 'Pengawasan Operasional Tower Crane & Pengangkatan Material Berat',
    target: '1. Tidak ada insiden sling putus atau material jatuh saat diangkat.\n2. Manuver pengangkatan aman tanpa melintasi permukiman umum.\n3. Alat angkat memenuhi standar kelaikan operasional.',
    supervisionProgram: '1. Memeriksa sertifikat SILO dan SIO Operator crane sebelum operasi dimulai.\n2. Melakukan verifikasi beban angkat terhadap tabel SWL.\n3. Mengawasi keterlibatan Rigger berlisensi dan Flagman saat lifting berlangsung.',
    benchmark: 'Seluruh pengangkatan memiliki lifting permit, SILO & SIO aktif dan terverifikasi.',
    pic: 'Inspector Peralatan & Ahli K3',
    schedule: 'Minggu ke-6 s/d Minggu ke-38',
    status: 'SEDANG_BERJALAN',
  },
];

export const initialPersonnel: Personnel[] = [
  {
    id: 'pers-001',
    projectId: 'proj-001',
    name: 'Ir. Hendra Wijaya, ST., MT.',
    nik: '3174091508750002',
    position: 'Kepala Pengawas Pekerjaan (Team Leader)',
    education: 'S2 Teknik Sipil Rekayasa Struktur',
    fieldOfExpertise: 'Manajemen Rekayasa Konstruksi & Struktur Gedung',
    yearsOfExperience: 18,
    certificates: [
      {
        id: 'cert-001',
        personnelId: 'pers-001',
        certificateNumber: '1.2.201.2.145.09.102345',
        certificateType: 'SKA Ahli Madya Manajemen Konstruksi',
        issuingBody: 'LPJK / LPJK Pusat',
        issueDate: '2023-05-10',
        expiryDate: '2028-05-09',
        status: 'AKTIF',
      },
    ],
  },
  {
    id: 'pers-002',
    projectId: 'proj-001',
    name: 'Drs. Wahyu Prasetyo, ST.',
    nik: '3324081203800004',
    position: 'Penanggung Jawab Keselamatan Konstruksi (Ahli K3)',
    education: 'S1 Teknik Lingkungan / K3',
    fieldOfExpertise: 'Keselamatan Konstruksi & Sistem Manajemen K3',
    yearsOfExperience: 12,
    certificates: [
      {
        id: 'cert-002',
        personnelId: 'pers-002',
        certificateNumber: 'K3-KONST-UTAMA-2023-889',
        certificateType: 'SKA Ahli K3 Konstruksi - Jenjang 8',
        issuingBody: 'BNSP / Lembaga Sertifikasi Profesi Konstruksi',
        issueDate: '2023-08-14',
        expiryDate: '2028-08-13',
        status: 'AKTIF',
      },
    ],
  },
  {
    id: 'pers-003',
    projectId: 'proj-001',
    name: 'Rian Setyawan, ST.',
    nik: '3324052006880001',
    position: 'Quality Engineer / Quantity Engineer',
    education: 'S1 Teknik Sipil',
    fieldOfExpertise: 'Quality Control, Pengujian Beton, dan Material',
    yearsOfExperience: 8,
    certificates: [
      {
        id: 'cert-003',
        personnelId: 'pers-003',
        certificateNumber: 'SKA-SIPIL-MDY-2022-451',
        certificateType: 'SKA Ahli Madya Teknik Bangunan Gedung',
        issuingBody: 'LPJK',
        issueDate: '2022-11-20',
        expiryDate: '2027-11-19',
        status: 'AKTIF',
      },
    ],
  },
  {
    id: 'pers-004',
    projectId: 'proj-001',
    name: 'Faisal Akbar, ST.',
    nik: '3324110904920005',
    position: 'Inspeksi Engineer (Inspector Sipil & K3)',
    education: 'S1 Teknik Sipil',
    fieldOfExpertise: 'Inspeksi Lapangan & Scaffolding K3',
    yearsOfExperience: 6,
    certificates: [
      {
        id: 'cert-004',
        personnelId: 'pers-004',
        certificateNumber: 'PETUGAS-K3-2024-112',
        certificateType: 'Sertifikat Petugas Keselamatan Konstruksi',
        issuingBody: 'Kementerian PUPR Ditjen Bina Konstruksi',
        issueDate: '2024-03-15',
        expiryDate: '2027-03-14',
        status: 'AKTIF',
      },
    ],
  },
];

export const initialSafetyBudgets: SafetyBudget[] = [
  {
    id: 'bud-001',
    rkkId: 'rkk-001',
    orderNumber: 1,
    componentCategory: '1. Penyiapan Dokumen Penerapan SMKK',
    itemDescription: 'Penyusunan dan penggandaan Dokumen RKK Pengawasan/MK, SOP, dan formulir inspeksi K3',
    volume: 1,
    unit: 'Paket',
    unitPrice: 12500000,
    totalPrice: 12500000,
    notes: 'Mencakup 5 rangkap dokumen hardcopy resmi & software format digital',
  },
  {
    id: 'bud-002',
    rkkId: 'rkk-001',
    orderNumber: 2,
    componentCategory: '2. Sosialisasi, Promosi dan Pelatihan K3',
    itemDescription: 'Safety Induction, Safety Morning Talk, Spanduk & Poster K3 di kantor pengawas & lapangan',
    volume: 1,
    unit: 'Paket',
    unitPrice: 18000000,
    totalPrice: 18000000,
    notes: 'Pengadaan spanduk K3, baliho komitmen Zero Accident, materi induction',
  },
  {
    id: 'bud-003',
    rkkId: 'rkk-001',
    orderNumber: 3,
    componentCategory: '3. Alat Pelindung Kerja (APK) dan Alat Pelindung Diri (APD)',
    itemDescription: 'Paket APD Tim Pengawas (Safety Helmet class E, Safety Shoes steel toe, Rompi reflektif, Kacamata, Full Body Harness)',
    volume: 12,
    unit: 'Set',
    unitPrice: 1850000,
    totalPrice: 22200000,
    notes: 'Khusus untuk personil konsultan pengawas dan tamu dinas/PPK',
  },
  {
    id: 'bud-004',
    rkkId: 'rkk-001',
    orderNumber: 4,
    componentCategory: '4. Asuransi dan Perizinan K3',
    itemDescription: 'BPJS Ketenagakerjaan (JKK & JKM) Tim Konsultan Pengawas',
    volume: 10,
    unit: 'Bulan',
    unitPrice: 2500000,
    totalPrice: 25000000,
    notes: 'Perlindungan jaminan kecelakaan kerja selama masa kontrak pengawasan',
  },
  {
    id: 'bud-005',
    rkkId: 'rkk-001',
    orderNumber: 5,
    componentCategory: '5. Personel Keselamatan Konstruksi',
    itemDescription: 'Honorarium dan tunjangan operasional Ahli K3 Pengawasan & Petugas K3',
    volume: 10,
    unit: 'Bulan',
    unitPrice: 15000000,
    totalPrice: 150000000,
    notes: 'Penugasan penuh waktu (full-time) selama masa pelaksanaan pekerjaan konstruksi',
  },
  {
    id: 'bud-006',
    rkkId: 'rkk-001',
    orderNumber: 6,
    componentCategory: '6. Fasilitas Sarana, Prasarana dan Alat Kesehatan',
    itemDescription: 'Penyediaan Kotak P3K standar Tipe B, Tensimeter, Tabung Oksigen Portable, dan Alat Uji Alkohol/Narkoba berkala',
    volume: 1,
    unit: 'Paket',
    unitPrice: 9500000,
    totalPrice: 9500000,
    notes: 'Ditempatkan di Pos Pengawas Lapangan',
  },
  {
    id: 'bud-007',
    rkkId: 'rkk-001',
    orderNumber: 7,
    componentCategory: '7. Rambu dan Perlengkapan Lalu Lintas Lapangan',
    itemDescription: 'Traffic Cone, Safety Line, Rambu Peringatan Ketinggian & Rambu Arah Darurat',
    volume: 1,
    unit: 'Paket',
    unitPrice: 14000000,
    totalPrice: 14000000,
    notes: 'Penandaan zona bahaya pengawasan konstruksi',
  },
  {
    id: 'bud-008',
    rkkId: 'rkk-001',
    orderNumber: 8,
    componentCategory: '8. Konsultasi dengan Ahli Terkait Keselamatan Konstruksi',
    itemDescription: 'Jasa konsultansi ahli rekayasa tanah/lereng dan pengujian alat angkat independen',
    volume: 2,
    unit: 'Sesi',
    unitPrice: 7500000,
    totalPrice: 15000000,
    notes: 'Audit kelaikan scaffolding tinggi dan pondasi basement',
  },
  {
    id: 'bud-009',
    rkkId: 'rkk-001',
    orderNumber: 9,
    componentCategory: '9. Kegiatan dan Peralatan Terkait Pengendalian Risiko Keselamatan',
    itemDescription: 'Pengukuran kebisingan, uji pencemaran debu udara, dan simulasi tanggap darurat bersama Damkar',
    volume: 1,
    unit: 'Paket',
    unitPrice: 11000000,
    totalPrice: 11000000,
    notes: 'Pengujian lingkungan berkala sesuai RKPPL',
  },
];

export const initialOrgMembers: OrgMember[] = [
  {
    id: 'org-001',
    rkkId: 'rkk-001',
    positionTitle: 'Pimpinan Pengawasan (Team Leader)',
    personnelName: 'Ir. Hendra Wijaya, ST., MT.',
    reportsToPosition: 'Direksi Pekerjaan / Pengguna Jasa',
    duties: [
      'Memimpin dan mengkoordinasikan seluruh aktivitas pengawasan pelaksanaan pekerjaan konstruksi.',
      'Memastikan seluruh tim konsultan pengawas menjalankan pengendalian mutu, waktu, biaya, dan keselamatan konstruksi.',
      'Mengesahkan dokumen RKK Pengawasan dan menyampaikan laporan kinerja SMKK berkala kepada PPK.',
    ],
    responsibilities: [
      'Bertanggung jawab penuh atas keandalan dan kepatuhan pengawasan keselamatan di lapangan.',
      'Memberikan rekomendasi tertulis kepada PPK jika ditemukan potensi bahaya yang mengancam keselamatan pekerja.',
    ],
    authorities: [
      'Menerbitkan instruksi perbaikan atau penghentian sementara pekerjaan jika terjadi kondisi darurat/pelanggaran K3 berat.',
      'Menolak material atau peralatan yang tidak memenuhi standar mutu dan kelaikan operasi (SILO).',
    ],
  },
  {
    id: 'org-002',
    rkkId: 'rkk-001',
    positionTitle: 'Penanggung Jawab Keselamatan Konstruksi Pengawasan',
    personnelName: 'Drs. Wahyu Prasetyo, ST.',
    reportsToPosition: 'Pimpinan Pengawasan (Team Leader)',
    duties: [
      'Menyusun dan memutakhirkan tabel Identifikasi Bahaya dan Pengendalian Risiko Pengawasan.',
      'Melaksanakan inspeksi keselamatan harian dan mingguan bersama tim kontraktor.',
      'Memeriksa kelengkapan permohonan Surat Izin Kerja (Permit to Work) dan dokumen JSA sebelum pekerjaan berisiko dimulai.',
    ],
    responsibilities: [
      'Bertanggung jawab atas efektivitas pemantauan penerapan SMKK di lapangan.',
      'Menindaklanjuti setiap temuan ketidaksesuaian K3 dan memverifikasi tindakan koreksi kontraktor.',
    ],
    authorities: [
      'Memberikan rekomendasi persetujuan atau penolakan pengajuan izin kerja khusus (ketinggian, galian, hot work).',
      'Menghentikan aktivitas berisiko jika SOP keselamatan tidak dijalankan di lapangan.',
    ],
  },
  {
    id: 'org-003',
    rkkId: 'rkk-001',
    positionTitle: 'Quality Engineer / Quantity Engineer',
    personnelName: 'Rian Setyawan, ST.',
    reportsToPosition: 'Pimpinan Pengawasan (Team Leader)',
    duties: [
      'Mengawasi kesesuaian mutu material (baja, beton, bekisting) dengan RMPK dan spesifikasi teknis.',
      'Menyaksikan pengujian bahan di laboratorium dan uji kelaikan di lapangan.',
      'Memastikan aspek K4 terpenuhi dalam setiap proses pengujian dan pengukuran kuantitas pekerjaan.',
    ],
    responsibilities: [
      'Bertanggung jawab atas validitas data pengujian mutu dan kuantitas pekerjaan yang terpasang.',
    ],
    authorities: [
      'Menolak adukan beton yang tidak memenuhi nilai slump atau waktu setting time yang disyaratkan.',
    ],
  },
  {
    id: 'org-004',
    rkkId: 'rkk-001',
    positionTitle: 'Inspeksi Engineer (Inspector Lapangan)',
    personnelName: 'Faisal Akbar, ST.',
    reportsToPosition: 'Pimpinan Pengawasan (Team Leader)',
    duties: [
      'Melakukan pengawasan visual harian langsung di area galian, scaffolding, dan area erection.',
      'Mencatat kondisi dan tindakan tidak aman (unsafe act & unsafe condition) dalam buku harian pengawas.',
      'Mengambil dokumentasi foto progres dan temuan K3 di lapangan.',
    ],
    responsibilities: [
      'Memastikan arahan keselamatan konstruksi tersosialisasi ke mandor dan pekerja di zona pengawasannya.',
    ],
    authorities: [
      'Menegur pekerja yang tidak menggunakan APD wajib di area kerja.',
    ],
  },
];

export const initialSafetyDocuments: SafetyDocument[] = [
  {
    id: 'doc-001',
    projectId: 'proj-001',
    category: 'SOP',
    docNumber: 'SOP-PW-K3-001',
    title: 'Prosedur Operasional Standar Pengawasan Keselamatan Konstruksi Lapangan',
    revision: '00',
    effectiveDate: '2026-03-01',
    preparedBy: 'Ahli K3 Pengawasan',
    reviewedBy: 'Team Leader',
    approvedBy: 'PPK RSUD Kendal',
    status: 'APPROVED',
    contentSummary: 'Tata cara pemeriksaan rutin harian, koordinasi tanggap darurat, dan alur pelaporan insiden kepada Pengguna Jasa.',
  },
  {
    id: 'doc-002',
    projectId: 'proj-001',
    category: 'INSTRUKSI_KERJA',
    docNumber: 'IK-PW-K3-002',
    title: 'Instruksi Kerja Pengawasan Pekerjaan di Ketinggian & Pemasangan Scaffolding',
    revision: '01',
    effectiveDate: '2026-03-10',
    preparedBy: 'Inspector Sipil',
    reviewedBy: 'Ahli K3 Pengawasan',
    approvedBy: 'Team Leader',
    status: 'APPROVED',
    contentSummary: 'Checklist verifikasi struktur scaffolding, pipe clamp, jack base, tie back, toe-board, dan penempelan tag inspeksi.',
  },
  {
    id: 'doc-003',
    projectId: 'proj-001',
    category: 'FORM',
    docNumber: 'FRM-PW-PTW-003',
    title: 'Formulir Permohonan & Pengesahan Izin Kerja Khusus (Permit to Work)',
    revision: '00',
    effectiveDate: '2026-03-01',
    preparedBy: 'Ahli K3 Pengawasan',
    reviewedBy: 'Team Leader',
    approvedBy: 'PPK RSUD Kendal',
    status: 'APPROVED',
    contentSummary: 'Form rangkap 3 untuk izin kerja panas, ruang terbatas, galian >2m, dan pekerjaan malam hari.',
  },
];

export const initialInspections: Inspection[] = [
  {
    id: 'insp-001',
    projectId: 'proj-001',
    inspectionNumber: 'INSP-2026-09-001',
    date: '2026-09-14',
    location: 'Lantai 4 Zona B (Area Pengecoran Balok)',
    activity: 'Inspeksi Kesiapan K3 Sebelum Pengecoran Plat & Balok Lantai 4',
    inspectorName: 'Faisal Akbar, ST. & Drs. Wahyu Prasetyo, ST.',
    conditionDescription: 'Pekerjaan pembesian telah selesai 95%. Perancah pipa telah berdiri, namun di sisi barat belum dilengkapi safety net penangkap puing.',
    findings: 'Terdapat celah selebar 40 cm di tepi perancah luar tanpa handrail ganda dan toe-board pengaman.',
    identifiedRisk: 'Pekerja atau perkakas cor terjatuh ke lantai dasar yang dapat mengenai orang melintas.',
    correctiveAction: 'Pasang barikade bawah dan lengkapi toe-board serta safety net di seluruh tepi barat sebelum adukan beton tiba.',
    pic: 'Mandor Struktur PT Cipta Bangun Perkasa',
    deadline: '2026-09-14',
    status: 'CLOSED',
    photos: [
      {
        id: 'p-001',
        photoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
        caption: 'Pemasangan safety net dan toe-board pelindung tepi lantai cor.',
        date: '2026-09-14',
        location: 'Lantai 4 Zona B',
        coordinates: '-6.9205, 110.2054',
        uploaderName: 'Faisal Akbar, ST.',
      },
    ],
    createdAt: '2026-09-14T09:30:00Z',
  },
  {
    id: 'insp-002',
    projectId: 'proj-001',
    inspectionNumber: 'INSP-2026-09-002',
    date: '2026-09-16',
    location: 'Area Grounding Tower Crane & Panel Distribusi Listrik',
    activity: 'Pemeriksaan Rutin Mingguan Peralatan Angkat & Kelistrikan Proyek',
    inspectorName: 'Drs. Wahyu Prasetyo, ST.',
    conditionDescription: 'Panel listrik utama dalam kondisi baik dan terlindung hujan. Namun terdapat 1 kabel fleksibel pompa celup tanpa sambungan berisolasi standar.',
    findings: 'Kabel pompa air sambungan isolasi manual terendam sedikit air di parit drainase kerja.',
    identifiedRisk: 'Bahaya induksi arus bocor / sengatan listrik ke pekerja yang melangkah di area drainase.',
    correctiveAction: 'Ganti kabel utuh dengan soket industri tahan air (IP67) dan gantung kabel di atas tiang kayu pengarah.',
    pic: 'Supervisor ME Kontraktor Pelaksana',
    deadline: '2026-09-17',
    status: 'FOLLOW_UP',
    photos: [
      {
        id: 'p-002',
        photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
        caption: 'Pemeriksaan panel kelistrikan dan grounding tower crane.',
        date: '2026-09-16',
        location: 'Ground Area Crane',
        coordinates: '-6.9203, 110.2051',
        uploaderName: 'Drs. Wahyu Prasetyo, ST.',
      },
    ],
    createdAt: '2026-09-16T14:15:00Z',
  },
];

export const initialFindings: Finding[] = [
  {
    id: 'fnd-001',
    projectId: 'proj-001',
    findingNumber: 'FIND-K3-001',
    date: '2026-09-14',
    source: 'INSPEKSI_RUTIN',
    location: 'Lantai 4 Zona B',
    description: 'Tepi perancah sisi barat belum terpasang toe-board dan safety net penahan material jatuh.',
    priority: 'TINGGI',
    pic: 'Mandor Struktur PT Cipta Bangun Perkasa',
    deadline: '2026-09-14',
    correctiveActionPlan: 'Memasang jaring safety net mesh 2cm x 2cm dan papan kayu toe-board 20cm di sekeliling tepi.',
    completionProofUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?w=600&auto=format&fit=crop&q=80',
    completionDate: '2026-09-14',
    verifierName: 'Drs. Wahyu Prasetyo, ST.',
    status: 'CLOSED',
    photos: [],
  },
  {
    id: 'fnd-002',
    projectId: 'proj-001',
    findingNumber: 'FIND-K3-002',
    date: '2026-09-16',
    source: 'PATROLI_K3',
    location: 'Area Grounding Crane',
    description: 'Kabel pompa celup terdapat sambungan tidak standar berada di dekat genangan air.',
    priority: 'KRITIS',
    pic: 'Supervisor ME Kontraktor',
    deadline: '2026-09-17',
    correctiveActionPlan: 'Penggantian kabel utuh dan pemasangan pengait kabel gantung di atas 2 meter.',
    status: 'IN_PROGRESS',
    photos: [],
  },
];

export const initialJSA: JobSafetyAnalysis[] = [
  {
    id: 'jsa-001',
    projectId: 'proj-001',
    jsaNumber: 'JSA-RSUD-01',
    jobName: 'Pekerjaan Pengangkatan Material Berat dengan Tower Crane (Erection Besi Kolom & Bekisting)',
    workStage: 'Pekerjaan Struktur Atas',
    location: 'Area Lantai 4 & Radius Putar Crane',
    date: '2026-09-12',
    preparedBy: 'Joko Widodo (Pelaksana Utama Kontraktor)',
    reviewedBy: 'Drs. Wahyu Prasetyo, ST. (Ahli K3 Konsultan)',
    approvedBy: 'Ir. Hendra Wijaya, ST., MT. (Team Leader)',
    items: [
      {
        step: 1,
        workStep: 'Pemeriksaan harian kondisi sling, shackle, dan hook tower crane',
        hazard: 'Sling kawat terpelintir, kawat putus, safety latch pada hook aus',
        risk: 'Muatan terlepas saat diangkat dan jatuh menimpa pekerja',
        controlMeasure: 'Inspeksi 100% sling kawat sebelum dipakai, hanya gunakan sling dengan tag warna lolos inspeksi bulan ini',
        pic: 'Rigger & Inspector ME',
      },
      {
        step: 2,
        workStep: 'Pengikatan material (rigging) dan pemasangan tagline kendali ayunan',
        hazard: 'Ikatan longgar, muatan tidak seimbang, pekerja terjepit muatan',
        risk: 'Cedera tangan terjepit, besi batangan tergelincir dari ikatan',
        controlMeasure: 'Gunakan minimal 2 ikatan chocker hitch, pasang tali pandu (tagline) minimal 5 meter, dilarang memegang muatan langsung',
        pic: 'Rigger Berlisensi',
      },
      {
        step: 3,
        workStep: 'Manuver pengangkatan dan pemindahan beban ke lantai 4',
        hazard: 'Kecepatan angin melebihi 20 knot, visibilitas operator terhalang, blind spot',
        risk: 'Beban membentur struktur yang telah berdiri, crane hilang keseimbangan',
        controlMeasure: 'Gunakan radio komunikasi 2 arah (HT), hentikan operasi jika kecepatan angin > 20 knot, koordinasi via Flagman',
        pic: 'Operator Crane & Safety Officer',
      },
      {
        step: 4,
        workStep: 'Penerimaan muatan dan pelepasan kaitan di lantai 4',
        hazard: 'Pekerja berdiri di bawah muatan gantung (line of fire), pekerja di tepi plat tanpa pengaman',
        risk: 'Tertimpa beban jatuh atau pekerja terpeleset jatuh dari tepi lantai 4',
        controlMeasure: 'Penerima beban wajib memakai full body harness terkait lifeline, dilarang berdiri di bawah beban melayang',
        pic: 'Mandor Struktur & Inspector Lapangan',
      },
    ],
    status: 'APPROVED',
  },
];

export const initialWorkPermits: WorkPermit[] = [
  {
    id: 'ptw-001',
    projectId: 'proj-001',
    permitNumber: 'PTW-HEIGHT-2026-042',
    permitType: 'HEIGHT',
    location: 'Lantai 5 (Pekerjaan Pengecoran Balok Perimeter Luar)',
    startDate: '2026-09-17T08:00:00Z',
    endDate: '2026-09-17T17:00:00Z',
    applicantName: 'Teguh Prasetyo (Supervisor Struktur)',
    contractorTeam: 'Tim Struktur Plat & Balok (PT Cipta Bangun Perkasa)',
    workersCount: 16,
    safetyChecklist: [
      { question: 'Apakah scaffolding telah dipasang oleh Scaffolder berlisensi dan bertanda Green Tag?', isCompliant: true },
      { question: 'Apakah lifeline kawat baja dan angkur terpasang dengan kuat sesuai standar?', isCompliant: true },
      { question: 'Apakah seluruh pekerja telah mengikuti Safety Induction & TBM Ketinggian?', isCompliant: true },
      { question: 'Apakah safety net penangkap material di sisi luar telah terpasang rapat?', isCompliant: true },
      { question: 'Apakah kondisi fisik pekerja sehat (bebas vertigo dan tensi normal)?', isCompliant: true },
    ],
    requiredApd: [
      'Safety Helmet dengan chinstrap',
      'Full Body Harness double lanyard with shock absorber',
      'Safety Shoes Steel Toe',
      'Rompi Reflektif berstandar',
      'Sarung Tangan Karet/Bintik Grip',
    ],
    supervisorSign: 'Teguh Prasetyo',
    safetyOfficerSign: 'Drs. Wahyu Prasetyo, ST.',
    clientApproverSign: 'Ahmad Fauzi, ST., M.Eng.',
    status: 'APPROVED',
  },
  {
    id: 'ptw-002',
    projectId: 'proj-001',
    permitNumber: 'PTW-HOT-2026-018',
    permitType: 'HOT_WORK',
    location: 'Basement Lantai Dasar (Pemotongan Besi Kolom & Pengelasan Plat Sambung)',
    startDate: '2026-09-17T09:00:00Z',
    endDate: '2026-09-17T16:00:00Z',
    applicantName: 'Sugeng Widodo (Mandor Pembesian)',
    contractorTeam: 'Tim Fabrikasi Besi Tulangan',
    workersCount: 4,
    safetyChecklist: [
      { question: 'Apakah area radius 10 meter bebas dari bahan mudah terbakar (kayu, oli, solar)?', isCompliant: true },
      { question: 'Apakah APAR minimal 6 kg tipe Powder/CO2 tersedia siap pakai di lokasi?', isCompliant: true },
      { question: 'Apakah terpal tahan api (fire blanket) terpasang di sekeliling titik percikan?', isCompliant: true },
      { question: 'Apakah kabel las dalam kondisi prima tanpa sambungan telanjang?', isCompliant: true },
    ],
    requiredApd: [
      'Topeng Las / Kacamata Las Shade 10',
      'Sarung Tangan Kulit Panjang (Welding Gloves)',
      'Apron Kulit Dada',
      'Masker Partikel/Respirator Uap Logam',
    ],
    supervisorSign: 'Sugeng Widodo',
    safetyOfficerSign: 'Drs. Wahyu Prasetyo, ST.',
    status: 'APPROVED',
  },
];

export const initialWeeklyReports: WeeklyReport[] = [
  {
    id: 'wr-001',
    projectId: 'proj-001',
    reportNumber: 'LAP-MG-K3/2026/W28',
    weekNumber: 28,
    startDate: '2026-09-08',
    endDate: '2026-09-14',
    supervisionActivitiesSummary: 'Pengawasan pekerjaan pengecoran plat lantai 4 zona A & B, inspeksi scaffolding perimeter, pemeriksaan rutin tower crane, dan verifikasi 3 permohonan Surat Izin Kerja (PTW). Pelaksanaan toolbox meeting mingguan dengan topik pencegahan jatuh dari ketinggian.',
    inspectionsConductedCount: 6,
    openFindingsCount: 1,
    closedFindingsCount: 5,
    permitsIssuedCount: 8,
    safeManHours: 3840,
    incidentCount: 0,
    recommendations: 'Tingkatkan keteraturan tata graha (5R) sisa potongan kawat bendrat di lantai kerja dan pastikan penandaan kabel listrik di lantai tidak terlindas alat angkut.',
    preparedBy: 'Drs. Wahyu Prasetyo, ST. (Ahli K3 Konsultan)',
    approvedBy: 'Ir. Hendra Wijaya, ST., MT. (Team Leader)',
    status: 'APPROVED',
  },
];

export const initialMonthlyReports: MonthlyReport[] = [
  {
    id: 'mr-001',
    projectId: 'proj-001',
    reportNumber: 'LAP-BL-K3/2026/08',
    monthName: 'Agustus 2026',
    executiveSummary: 'Penerapan SMKK pada bulan Agustus 2026 berjalan secara konsisten dengan pencapaian Zero Accident. Total jam kerja selamat mencapai 16.480 jam orang. Seluruh personil inti pengawasan hadir lengkap di lapangan.',
    severityRate: 0,
    frequencyRate: 0,
    zeroAccidentStatus: true,
    inspectionsSummary: 'Telah dilaksanakan 24 sesi inspeksi keselamatan konstruksi meliputi pekerjaan pembesian, bekisting, operasional crane, dan kebersihan lingkungan kerja.',
    findingsAnalysis: 'Ditemukan 18 ketidaksesuaian minor (terkait kelengkapan APD kacamata dan penempatan APAR). 17 temuan telah diselesaikan (closed) dan 1 temuan dalam proses tindak lanjut.',
    testingCommissioningSummary: 'Telah dilakukan pengujian slump beton 18 batch dan uji tekan silinder 28 hari dengan hasil memenuhi standar f\'c 30 MPa.',
    kpiScore: 91.5,
    recommendations: 'Mempersiapkan prosedur tanggap darurat cuaca ekstrem menyongsong musim penghujan bulan Oktober-November.',
    preparedBy: 'Drs. Wahyu Prasetyo, ST.',
    approvedBy: 'Ir. Hendra Wijaya, ST., MT.',
    status: 'APPROVED',
  },
];

export const initialTestingCommissioning: TestingCommissioning[] = [
  {
    id: 'tc-001',
    projectId: 'proj-001',
    itemNumber: 'TC-STR-2026-015',
    workDescription: 'Pengujian Slump Flow dan Kuat Tekan Beton Silinder Mutu f\'c 30 MPa Plat Lantai 4',
    testDate: '2026-09-14',
    location: 'Laboratorium Uji Bahan Lapangan RSUD Kendal',
    method: 'SNI 1972:2008 & SNI 1974:2011',
    appliedStandard: 'Spesifikasi Teknis Divisi 7 Pekerjaan Beton',
    testResult: 'LAIK_OPERASI',
    certificateOrDocRef: 'CERT-LAB-BETON-KDL-2026-441',
    notes: 'Nilai slump rata-rata 12 ± 2 cm, kuat tekan umur 7 hari mencapai 22.4 MPa (> 70% kuat rencana)',
    recommendations: 'Pekerjaan pengecoran balok dan plat lantai 4 dapat dilanjutkan sesuai gambar rencana.',
    inspectorName: 'Rian Setyawan, ST. (Quality Engineer)',
    status: 'COMPLETED',
  },
  {
    id: 'tc-002',
    projectId: 'proj-001',
    itemNumber: 'TC-EQ-2026-004',
    workDescription: 'Uji Kelaikan Operasi (Load Test) Tower Crane Potain MC85B Beban 1.5 Ton Radius 40 M',
    testDate: '2026-08-25',
    location: 'Tapak Tower Crane Proyek RSUD Kendal',
    method: 'Uji Statis 125% SWL & Uji Dinamis 110% SWL',
    appliedStandard: 'Permenaker No. 8 Tahun 2020 & Standar Pabrikan Potain',
    testResult: 'LAIK_OPERASI',
    certificateOrDocRef: 'SILO-DISNAKER-JTG-566/TC/2026',
    notes: 'Semua sistem pengereman, limit switch ketinggian, dan cut-off beban berlebih berfungsi akurat.',
    recommendations: 'Peralatan dinyatakan laik operasi hingga 25 Agustus 2027.',
    inspectorName: 'Drs. Wahyu Prasetyo, ST. & Penguji Kemnaker',
    status: 'COMPLETED',
  },
];

export const initialFinalEvaluation: FinalEvaluation = {
  id: 'fe-001',
  projectId: 'proj-001',
  completionDate: '2026-09-17',
  overallComplianceScore: 93.4,
  totalInspections: 58,
  totalFindings: 42,
  resolvedFindings: 41,
  zeroAccidentAchieved: true,
  environmentalCompliance: 'Pengolahan limbah air cor terkendali dalam kolam sedimentasi, penumpukan material tidak mengganggu akses publik.',
  finalRecommendations: 'Dokumentasikan seluruh rekaman inspeksi, izin kerja, dan sertifikat pengujian sebagai lampiran As-Built Drawing dan Dokumen Serah Terima Pertama (PHO).',
  evaluatorName: 'Ir. Hendra Wijaya, ST., MT.',
  clientReviewNotes: 'Pengawasan keselamatan konstruksi oleh konsultan berjalan sangat baik dan tertib administrasi.',
};

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-17T04:15:00Z',
    userName: 'Ir. Hendra Wijaya, ST., MT.',
    userRole: 'TEAM_LEADER',
    action: 'APPROVAL',
    module: 'Izin Kerja',
    recordIdentifier: 'PTW-HEIGHT-2026-042',
    description: 'Menyetujui permohonan Surat Izin Kerja di Ketinggian Lantai 5',
    ipAddress: '180.252.88.14',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-16T14:30:00Z',
    userName: 'Drs. Wahyu Prasetyo, ST.',
    userRole: 'SAFETY_ENGINEER',
    action: 'CREATE',
    module: 'Inspeksi Lapangan',
    recordIdentifier: 'INSP-2026-09-002',
    description: 'Mencatat hasil inspeksi kelistrikan dan grounding crane',
    ipAddress: '180.252.88.14',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-14T10:00:00Z',
    userName: 'Ir. Hendra Wijaya, ST., MT.',
    userRole: 'TEAM_LEADER',
    action: 'GENERATE_PDF',
    module: 'RKK Dokumen',
    recordIdentifier: 'RKK-MK/RSUD-KDL/2026/01',
    description: 'Mencetak dokumen resmi RKK Konsultansi Pengawasan A4 sesuai format Permen PUPR No. 10/2021',
    ipAddress: '180.252.88.14',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-001',
    title: 'Izin Kerja Menunggu Verifikasi',
    message: 'Izin Kerja di Ketinggian Lantai 5 (PTW-HEIGHT-2026-042) telah diajukan kontraktor.',
    type: 'WARNING',
    timestamp: '10 menit yang lalu',
    isRead: false,
    linkTo: 'monitoring-permits',
  },
  {
    id: 'notif-002',
    title: 'Tindak Lanjut Temuan K3',
    message: 'Temuan Kritis Grounding Kabel Crane (FIND-K3-002) jatuh tempo hari ini.',
    type: 'ALERT',
    timestamp: '1 jam yang lalu',
    isRead: false,
    linkTo: 'monitoring-findings',
  },
  {
    id: 'notif-003',
    title: 'Dokumen RKK Disetujui PPK',
    message: 'Dokumen RKK Pembangunan RSUD Dr. Soewondo telah ditandatangani dan disetujui Pengguna Jasa.',
    type: 'SUCCESS',
    timestamp: 'Kemarin',
    isRead: true,
    linkTo: 'rkk-document',
  },
];

export const initialTemplates: RKKTemplate[] = [
  {
    id: 'tpl-gedung',
    name: 'Template RKK Pengawasan Gedung Bertingkat',
    category: 'GEDUNG',
    description: 'Template acuan pengawasan keselamatan untuk konstruksi gedung perkantoran, rumah sakit, kampus, dan rusun.',
    sampleHazards: [
      {
        activityDescription: 'Pengawasan Pekerjaan Galian Pondasi Basement Dalam (> 3m)',
        supervisionActivity: 'Pemeriksaan lereng shoring dan dewatering',
        hazardIdentification: 'Longsor dinding galian, gas beracun',
        riskDescription: 'Pekerja tertimbun material tanah',
        riskLevel: 'Sedang',
      },
      {
        activityDescription: 'Pengawasan Pengecoran Struktur Lantai Atas',
        supervisionActivity: 'Pemeriksaan perancah dan safety net perimeter',
        hazardIdentification: 'Jatuh dari ketinggian, robohnya bekisting',
        riskDescription: 'Kecelakaan fatal jatuh dari elevasi tinggi',
        riskLevel: 'Besar',
      },
    ],
    sampleRegulations: [
      {
        methodDescription: 'Keselamatan Umum Konstruksi Gedung',
        regulationTitle: 'Permen PUPR No. 10 Tahun 2021 tentang Pedoman SMKK',
        numberAndYear: 'Permen PUPR 10/2021',
        articleClause: 'Lampiran D.1 (RKK Pengawasan)',
      },
    ],
    samplePrograms: [
      {
        activityDescription: 'Pengawasan Scaffolding & Bekerja di Ketinggian',
        target: 'Zero accident jatuh dari ketinggian',
        supervisionProgram: 'Inspeksi mingguan scaffolding & tagging hijau',
        benchmark: '100% perancah bertanda Green Tag',
        schedule: 'Mingguan',
      },
    ],
  },
  {
    id: 'tpl-jalan',
    name: 'Template RKK Pengawasan Preservasi / Pembangunan Jalan',
    category: 'JALAN',
    description: 'Template acuan pengawasan K3 jalan raya, perkerasan aspal/rigid, manajemen lalu lintas (traffic management) dan alat berat grader/roller.',
    sampleHazards: [
      {
        activityDescription: 'Pengawasan Pekerjaan Penghamparan Aspal Panas (Hotmix)',
        supervisionActivity: 'Pengawasan temperatur aspal, APD masker/sepatu safety pekerja, dan jarak manuver tandem roller',
        hazardIdentification: 'Luka bakar aspal cair, paparan uap hidrokarbon, tertabrak alat pemadat',
        riskDescription: 'Cedera luka bakar serius, gangguan pernafasan',
        riskLevel: 'Sedang',
      },
      {
        activityDescription: 'Pengawasan Manajemen Rekayasa Lalu Lintas Proyek (Traffic Management)',
        supervisionActivity: 'Verifikasi perambuan sementara, flagman, dan barrier pembatas jalur',
        hazardIdentification: 'Kendaraan umum melaju kencang menabrak pekerja di zona transisi',
        riskDescription: 'Tabrakan lalu lintas berakibat fatal',
        riskLevel: 'Besar',
      },
    ],
    sampleRegulations: [
      {
        methodDescription: 'Keselamatan Lalu Lintas di Area Konstruksi',
        regulationTitle: 'UU No. 22 Tahun 2009 tentang Lalu Lintas dan Angkutan Jalan',
        numberAndYear: 'UU No. 22/2009',
        articleClause: 'Pasal 99 & 100',
      },
    ],
    samplePrograms: [
      {
        activityDescription: 'Pengawasan Manajemen Lalu Lintas',
        target: 'Kelancaran arus lalu lintas & keselamatan pekerja di jalan aktif',
        supervisionProgram: 'Pemeriksaan harian rambu peringatan awal dan flagman',
        benchmark: 'Zero accident tabrakan di zona kerja',
        schedule: 'Setiap Hari',
      },
    ],
  },
  {
    id: 'tpl-jembatan',
    name: 'Template RKK Pengawasan Pembangunan Jembatan',
    category: 'JEMBATAN',
    description: 'Template acuan pengawasan K3 pondasi tiang pancang, abutment/pilar jembatan, erection girder baja/beton di atas sungai.',
    sampleHazards: [
      {
        activityDescription: 'Pengawasan Erection Girder Jembatan dengan Launcher / Dual Crane',
        supervisionActivity: 'Verifikasi stabilitas dudukan crane, lifting plan, dan penutupan jalur di bawah bentang jembatan',
        hazardIdentification: 'Girder tergelincir, sling crane putus, kegagalan bracing jembatan',
        riskDescription: 'Runtuhnya girder jembatan menimpa pekerja/sungai',
        riskLevel: 'Besar',
      },
    ],
    sampleRegulations: [
      {
        methodDescription: 'Pengawasan Erection Girder',
        regulationTitle: 'Permenaker No. 8 Tahun 2020 tentang Pesawat Angkat dan Angkut',
        numberAndYear: 'Permenaker 8/2020',
        articleClause: 'Pasal 137 s/d 150',
      },
    ],
    samplePrograms: [
      {
        activityDescription: 'Erection Girder Jembatan',
        target: 'Semua balok girder terpasang presisi tanpa insiden',
        supervisionProgram: 'Pemeriksaan lifting permit dan pengawasan manuver girder',
        benchmark: 'Girder terpasang 100% aman di perletakan elastomeric bearing',
        schedule: 'Sesuai Tahap Erection',
      },
    ],
  },
];
